
name: CI
on:
 push: 
 branches: [main]

workflow_dispatch:
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
   - name: Print node version
     run: node --version
   - name: Print NPM version
     run: npm --version
   - name: Print pwd
     run: pwd